### ISSUE TITLE
Mark 66.0.1 as a sec driven release in product details

### ISSUE THREAD

**Issue by sylvestre** [mozilla/release-mgmt-projects#99]

**Comment by sylvestre** [comment]
It isn't the case currently:
![image](https://user-images.githubusercontent.com/733326/55318147-56c0ed80-5472-11e9-8688-850850a3f493.png)

Should be true with a link to the sec adv
@lizzard could you please fix that? Thanks

**Comment by sylvestre** [comment]
Please also update the description :)

**Comment by lizzard** [comment]
OK, marked them both as Pwn2Own 2019. I don't think there is a blog post associated with it.

**Comment by sylvestre** [comment]
The sec adv would have been fine too
